export const TABLES = {
  teams: ['id', 'name', 'engine', 'drivers', 'notes'],
  drivers: ['id', 'name', 'number', 'team_id', 'nationality', 'wins', 'podiums', 'points', 'notes'],
  tracks: ['id', 'name', 'country', 'city', 'lap_length', 'notes'],
  weekend_format: ['type', 'sessions', 'sprint_points', 'parc_ferme_after'],
  race_weekend: ['id', 'grand_prix', 'circuit_id', 'date', 'format'],
  sessions: ['fp1', 'fp2', 'fp3', 'qualifying', 'sprint_shootout', 'sprint', 'race'],
  raceJournal: [
    'id',
    'grand_prix',
    'circuit_id',
    'date',
    'weather',
    'pole_position',
    'fastest_lap',
    'driver_of_day',
    'p1_driver',
    'p2_driver',
    'p3_driver',
    'p4_driver',
    'p5_driver',
    'p6_driver',
    'p7_driver',
    'p8_driver',
    'p9_driver',
    'p10_driver',
    'p11_driver',
    'p12_driver',
    'safety_cars',
    'red_flags',
    'race_rating',
    'best_overtake',
    'surprise',
    'disappointment',
    'notes',
  ],
  favorites: ['id', 'type', 'referenceId'],
}
